import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Seu Título da Página</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        {/* Outros links ou tags meta podem ser adicionados aqui */}
      </Head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
